# isksync/constants.py

# TaxCycle status choices
TAXCYCLE_STATUS_PENDING = "PENDING"
TAXCYCLE_STATUS_PAID = "PAID"
TAXCYCLE_STATUS_WRITTEN_OFF = "WRITTEN_OFF"
TAXCYCLE_STATUS_CHOICES = [
    (TAXCYCLE_STATUS_PENDING, "Pending"),
    (TAXCYCLE_STATUS_PAID, "Paid"),
    (TAXCYCLE_STATUS_WRITTEN_OFF, "Written Off"),
]

# TaxCycleObligation status choices
OBLIGATION_STATUS_PENDING = "PENDING"
OBLIGATION_STATUS_COMPLETED = "COMPLETED"
OBLIGATION_STATUS_FAILED = "FAILED"
OBLIGATION_STATUS_CHOICES = [
    (OBLIGATION_STATUS_PENDING, "Pending"),
    (OBLIGATION_STATUS_COMPLETED, "Completed"),
    (OBLIGATION_STATUS_FAILED, "Failed"),
]

# DiscordNotificationConfig severity choices
SEVERITY_LOW = "LOW"
SEVERITY_MEDIUM = "MEDIUM"
SEVERITY_HIGH = "HIGH"
SEVERITY_CHOICES = [
    (SEVERITY_LOW, "Low - Info only"),
    (SEVERITY_MEDIUM, "Medium - Warning"),
    (SEVERITY_HIGH, "High - Critical"),
]

# DiscordNotificationLog notification types
NOTIF_BATCHED_ADVANCE = "BATCHED_ADVANCE"
NOTIF_BATCHED_DUE = "BATCHED_DUE"
NOTIF_BATCHED_OVERDUE = "BATCHED_OVERDUE"
NOTIF_TEST_ADVANCE = "TEST_ADVANCE"
NOTIF_TEST_DUE = "TEST_DUE"
NOTIF_TEST_OVERDUE = "TEST_OVERDUE"
NOTIF_ADMIN_ADVANCE = "ADMIN_ADVANCE"
NOTIF_ADMIN_DUE = "ADMIN_DUE"
NOTIF_ADMIN_OVERDUE = "ADMIN_OVERDUE"
NOTIFICATION_TYPE_CHOICES = [
    (NOTIF_BATCHED_ADVANCE, "Batched Advance Notice"),
    (NOTIF_BATCHED_DUE, "Batched Due Date"),
    (NOTIF_BATCHED_OVERDUE, "Batched Overdue"),
    (NOTIF_TEST_ADVANCE, "Test Advance Notice"),
    (NOTIF_TEST_DUE, "Test Due Date"),
    (NOTIF_TEST_OVERDUE, "Test Overdue"),
    (NOTIF_ADMIN_ADVANCE, "Admin Advance Notice"),
    (NOTIF_ADMIN_DUE, "Admin Due Date"),
    (NOTIF_ADMIN_OVERDUE, "Admin Overdue"),
]
