# Generated by Django 4.2.23 on 2025-10-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isksync', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxcycle',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('WRITTEN_OFF', 'Written Off')], default='PENDING', max_length=15),
        ),
    ]
