# Generated by Django 4.2.23 on 2026-02-22 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groupmanagement', '0019_adding_restricted_to_groups'),
        ('isksync', '0002_alter_taxcycle_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemownership',
            name='auth_group',
            field=models.ForeignKey(blank=True, help_text='Alliance Auth group that contains users with access to this system', null=True, on_delete=django.db.models.deletion.SET_NULL, to='groupmanagement.authgroup'),
        ),
    ]
