# Generated by Django 4.2.28 on 2026-05-04 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eve_sde', '0018_blueprintactivity_blueprintactivityproduct_and_more'),
        ('isksync', '0003_alter_systemownership_auth_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemownership',
            name='system',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='eve_sde.solarsystem'),
        ),
    ]
